name: sechdule job
on:
  schedule:
      - cron: "13 15 06 11 04"
jobs:
  message:
    runs-on: ubuntu-latest
    steps: 
      - name: print-greeting
        run: echo "its schedule"
        
      
  
    
